version: '3'

volumes:
  tracker-data:

services:
  database:
    container_name: tracker_database
    image: postgres:16-alpine
    restart: always
    volumes:
      - tracker-data:/data/postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/data/postgres

  tracker:
    image: ghcr.io/azpha/subscription-tracker:latest
    ports:
      - "3000:3000"
    depends_on:
      - database
    environment:
      - DISCORD_WEBHOOK=https://discord.com/api/webhooks/
      - TIMEZONE=America/New_York