volumes:
  subs-db:

services:
  subscription-tracker:
    image: ghcr.io/azpha/subscription-tracker:latest
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - "subs:/app"
    environment:
      - BASE_URL=https://subs.domain.tld # the url of this instance to link to in ntfy/discord notifications
