networks:
  subs-network:
    name: subs-network
volumes:
  subs-db:

services:
  db:
    image: mariadb
    restart: unless-stopped
    networks:
      - subs-network
    volumes:
      - subs-db:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: super_secret
      MARIADB_USER: subscription
      MARIADB_PASSWORD: super_secret
      MARIADB_DATABASE: subscription
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  subscription-tracker:
    build: .
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    networks:
      - subs-network
    ports:
      - 3000:3000
      - 3001:3001
    environment:
      - DATABASE_URL=mysql://subscription:super_secret@db:3306/subscription
      - DISCORD_WEBHOOK=https://discord.com/api/webhooks/1368364160332730498/DPr4RLMuR_588C3CY0lBvNZjiZJm5koXDvwJEjXdbE7sgLPt2JyacWF5d1DiRkPfCSGC